
development:
  adapter: mysql2
  encoding: utf8
  database: proficiency-test_development
  username: root
  password: 
  host: localhost



test:
  adapter: mysql2
  encoding: utf8
  database: proficiency-test_test
  username: root
  password: 
  host: localhost