
development:
  adapter: mysql2
  encoding: utf8
  database: proficiency-test_development
  username: root
  password: 
  host: localhost



test:
  adapter: mysql2
  encoding: utf8
  database: proficiency-test_test
  username: root
  password: 
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: d9etlm5d67kulr
  username: nvkwpcnsghhzai
  password: 7GW0l6snlk8FFWXcXUkTEgPomZ
  host: ec2-54-83-17-8.compute-1.amazonaws.com
  port: 5432
  pool: 10